services:
  - type: web
    name: jogo-de-luta
    runtime: node
    buildCommand: npm install --prefix client && npm run build --prefix client && npm ci --prefix server
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
